# Generated by Django 4.1.7 on 2023-06-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_filiere_specialite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20, verbose_name='Libellé')),
            ],
            options={
                'verbose_name_plural': 'Niveau',
            },
        ),
    ]
