# Generated by Django 4.1.7 on 2023-06-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_etudiant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={'verbose_name_plural': 'Etudiant'},
        ),
    ]
