# Generated by Django 4.1.7 on 2023-06-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_etudiant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='ce',
            field=models.FileField(max_length=150, upload_to='carte_ce', verbose_name='Carte etudiante'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='oni',
            field=models.FileField(max_length=150, upload_to='carte_cni', verbose_name="Pièce nationale d'identité"),
        ),
    ]
